package Biblioteca;


/**
* Biblioteca/GestionBibliotecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* s�bado 16 de marzo de 2024 18H27' CET
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public interface GestionBibliotecaOperations 
{

  // Busca un libro por título y devuelve los detalles del libro
  Biblioteca.Libro buscarLibro (String titulo);

  // Presta un libro, cambiando su estado a no disponible
  boolean prestarLibro (String ISBN);

  // Devuelve un libro, cambiando su estado a disponible
  boolean devolverLibro (String ISBN);

  // Devuelve una lista de todos los libros de la biblioteca
  Biblioteca.Libro[] listarLibros ();

  // Añade un comentario y calificación a un libro
  boolean anadirComentarioYCalificacion (String ISBN, String comentario, float calificacion);

  // Mostrar comentarios de un libro
  String[] mostrarComentarios (String ISBN);
} // interface GestionBibliotecaOperations
