package Biblioteca;


/**
* Biblioteca/Libro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* sábado 16 de marzo de 2024 18H27' CET
*/

public final class Libro implements org.omg.CORBA.portable.IDLEntity
{
  public String titulo = null;
  public String autor = null;
  public String ISBN = null;
  public float calificacion = (float)0;
  public String comentarios[] = null;
  public boolean estaDisponible = false;

  public Libro ()
  {
  } // ctor

  public Libro (String _titulo, String _autor, String _ISBN, float _calificacion, String[] _comentarios, boolean _estaDisponible)
  {
    titulo = _titulo;
    autor = _autor;
    ISBN = _ISBN;
    calificacion = _calificacion;
    comentarios = _comentarios;
    estaDisponible = _estaDisponible;
  } // ctor

} // class Libro
