package Biblioteca;


/**
* Biblioteca/LibroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* sábado 16 de marzo de 2024 18H27' CET
*/

abstract public class LibroHelper
{
  private static String  _id = "IDL:Biblioteca/Libro:1.0";

  public static void insert (org.omg.CORBA.Any a, Biblioteca.Libro that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Biblioteca.Libro extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "titulo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "autor",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "ISBN",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[3] = new org.omg.CORBA.StructMember (
            "calificacion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "comentarios",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[5] = new org.omg.CORBA.StructMember (
            "estaDisponible",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Biblioteca.LibroHelper.id (), "Libro", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Biblioteca.Libro read (org.omg.CORBA.portable.InputStream istream)
  {
    Biblioteca.Libro value = new Biblioteca.Libro ();
    value.titulo = istream.read_string ();
    value.autor = istream.read_string ();
    value.ISBN = istream.read_string ();
    value.calificacion = istream.read_float ();
    int _len0 = istream.read_long ();
    value.comentarios = new String[_len0];
    for (int _o1 = 0;_o1 < value.comentarios.length; ++_o1)
      value.comentarios[_o1] = istream.read_string ();
    value.estaDisponible = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Biblioteca.Libro value)
  {
    ostream.write_string (value.titulo);
    ostream.write_string (value.autor);
    ostream.write_string (value.ISBN);
    ostream.write_float (value.calificacion);
    ostream.write_long (value.comentarios.length);
    for (int _i0 = 0;_i0 < value.comentarios.length; ++_i0)
      ostream.write_string (value.comentarios[_i0]);
    ostream.write_boolean (value.estaDisponible);
  }

}
