package Biblioteca;


/**
* Biblioteca/ListaComentariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* sábado 16 de marzo de 2024 18H27' CET
*/

public final class ListaComentariosHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListaComentariosHolder ()
  {
  }

  public ListaComentariosHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Biblioteca.ListaComentariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Biblioteca.ListaComentariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Biblioteca.ListaComentariosHelper.type ();
  }

}
