package Biblioteca;


/**
* Biblioteca/ListaLibrosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* sábado 16 de marzo de 2024 18H27' CET
*/

public final class ListaLibrosHolder implements org.omg.CORBA.portable.Streamable
{
  public Biblioteca.Libro value[] = null;

  public ListaLibrosHolder ()
  {
  }

  public ListaLibrosHolder (Biblioteca.Libro[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Biblioteca.ListaLibrosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Biblioteca.ListaLibrosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Biblioteca.ListaLibrosHelper.type ();
  }

}
